// The screens of a project workspace, in workflow order. Each path is a route under /projects/:projectId/.
export const PROJECT_TABS = [
  { path: 'setup', label: '1. Project Setup' },
  { path: 'topic', label: '2. Topic & Feasibility' },
  { path: 'question', label: '3. Review Question' },
  { path: 'protocol', label: '4. Eligibility Criteria' },
  { path: 'analysis-plan', label: '5. Analysis Plan' },
  { path: 'protocol-document', label: '6. Protocol Document' },
  { path: 'registration', label: '7. Registration & Export' },
  { path: 'search', label: '8. Database Search & Import' },
  { path: 'other-sources', label: '9. Citations & Grey Literature' },
  { path: 'deduplication', label: '10. Deduplication' },
  { path: 'screening', label: '11. Abstract Screening' },
  { path: 'full-texts', label: '12. Full Texts' },
  { path: 'full-text-screening', label: '13. Full-Text Screening' },
  { path: 'studies', label: '14. Studies & Reports' },
  { path: 'extraction-fields', label: '15. Extraction Form' },
  { path: 'extraction', label: '16. Data Extraction' },
  { path: 'prisma', label: '17. PRISMA Flow Diagram' },
  { path: 'risk-of-bias', label: '18. Risk of Bias & Quality' },
  { path: 'synthesis', label: '19. Statistical Synthesis' },
  { path: 'certainty', label: '20. Certainty & Interpretation' },
  { path: 'manuscript', label: '21. Manuscript' },
  { path: 'publication', label: '22. Submission & Publication' },
  { path: 'living', label: '23. Living Review' },
  { path: 'team', label: '24. Team & Tasks' },
  { path: 'governance', label: '25. AI Governance' },
  { path: 'interop', label: '26. Export & Integrations' },
] as const;

export type ProjectTab = (typeof PROJECT_TABS)[number]['path'];
