"""Persist the review workflow: protocols, criteria, searches, records, AI runs, decisions, and audit trail.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-14 20:53:25.181634
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Copied rather than imported from project_defaults.py so this migration never changes when the app does.
DEFAULT_EXTRACTION_FIELDS = ["Sample Size", "Mean Age", "Primary Outcome Result", "Adverse Events"]


def _backfill_project_defaults() -> None:
    """Give existing projects the protocol row and starting extraction fields that new projects are created with."""
    connection = op.get_bind()
    now = datetime.now(UTC)
    for (project_id,) in connection.execute(sa.text("SELECT id FROM projects")).all():
        connection.execute(
            sa.text(
                "INSERT INTO protocols (project_id, review_type, framework, description, suggested_criteria, "
                "extraction_outline, rob_tool, updated_at) "
                "VALUES (:project_id, 'Systematic Review', 'PICO', '', '', '', 'ROB-2', :now)"
            ),
            {"project_id": project_id, "now": now},
        )
        for position, name in enumerate(DEFAULT_EXTRACTION_FIELDS):
            connection.execute(
                sa.text(
                    "INSERT INTO extraction_fields (project_id, name, position) VALUES (:project_id, :name, :position)"
                ),
                {"project_id": project_id, "name": name, "position": position},
            )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=40), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_project_id"), ["project_id"], unique=False)

    op.create_table(
        "criteria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_criteria_project_id"), ["project_id"], unique=False)

    op.create_table(
        "extraction_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_extraction_field_name"),
    )
    with op.batch_alter_table("extraction_fields", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extraction_fields_project_id"), ["project_id"], unique=False)

    op.create_table(
        "protocols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("review_type", sa.String(length=50), nullable=False),
        sa.Column("framework", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("suggested_criteria", sa.Text(), nullable=False),
        sa.Column("extraction_outline", sa.Text(), nullable=False),
        sa.Column("rob_tool", sa.String(length=30), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "search_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("database", sa.String(length=100), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_strategies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_strategies_project_id"), ["project_id"], unique=False)

    op.create_table(
        "search_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("database", sa.String(length=200), nullable=False),
        sa.Column("source_label", sa.String(length=300), nullable=False),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("executed_by_id", sa.Integer(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["executed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["search_strategies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("search_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_search_runs_project_id"), ["project_id"], unique=False)

    op.create_table(
        "records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("search_run_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), nullable=False),
        sa.Column("year", sa.String(length=20), nullable=False),
        sa.Column("venue", sa.Text(), nullable=False),
        sa.Column("doi", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("duplicate_of_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["duplicate_of_id"], ["records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["search_run_id"], ["search_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_records_doi"), ["doi"], unique=False)
        batch_op.create_index(batch_op.f("ix_records_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_records_search_run_id"), ["search_run_id"], unique=False)

    op.create_table(
        "ai_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("task", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("triggered_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_runs_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_runs_record_id"), ["record_id"], unique=False)

    op.create_table(
        "screening_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "stage", "reviewer_id", name="uq_screening_decision"),
    )
    with op.batch_alter_table("screening_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_screening_decisions_record_id"), ["record_id"], unique=False)

    op.create_table(
        "appraisal_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.Integer(), nullable=False),
        sa.Column("tool", sa.String(length=30), nullable=False),
        sa.Column("judgments", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ai_run_id"),
    )
    op.create_table(
        "extraction_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["extraction_fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extraction_suggestions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_extraction_suggestions_ai_run_id"), ["ai_run_id"], unique=False)

    op.create_table(
        "screening_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("supporting_quote", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ai_run_id"),
    )
    op.create_table(
        "synthesis_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("ai_run_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("synthesis_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_synthesis_reports_project_id"), ["project_id"], unique=False)

    # Rows created before migrations existed may lack created_at, which becomes required below.
    op.execute("UPDATE projects SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE users SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)

    # ### end Alembic commands ###

    _backfill_project_defaults()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("synthesis_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_synthesis_reports_project_id"))

    op.drop_table("synthesis_reports")
    op.drop_table("screening_suggestions")
    with op.batch_alter_table("extraction_suggestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_suggestions_ai_run_id"))

    op.drop_table("extraction_suggestions")
    op.drop_table("appraisal_suggestions")
    with op.batch_alter_table("screening_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_screening_decisions_record_id"))

    op.drop_table("screening_decisions")
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_runs_record_id"))
        batch_op.drop_index(batch_op.f("ix_ai_runs_project_id"))

    op.drop_table("ai_runs")
    with op.batch_alter_table("records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_records_search_run_id"))
        batch_op.drop_index(batch_op.f("ix_records_project_id"))
        batch_op.drop_index(batch_op.f("ix_records_doi"))

    op.drop_table("records")
    with op.batch_alter_table("search_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_runs_project_id"))

    op.drop_table("search_runs")
    with op.batch_alter_table("search_strategies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_strategies_project_id"))

    op.drop_table("search_strategies")
    op.drop_table("protocols")
    with op.batch_alter_table("extraction_fields", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extraction_fields_project_id"))

    op.drop_table("extraction_fields")
    with op.batch_alter_table("criteria", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_criteria_project_id"))

    op.drop_table("criteria")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_project_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
