"""Manuscripts, references, checklists, approvals; journals, submission packages, deposits, peer review; surveillance,
alerts, impact assessments, and releases

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-15 19:35:53.508535
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("openalex_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column(
            "issns", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("publisher", sa.String(length=500), server_default="", nullable=False),
        sa.Column("homepage", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("is_oa", sa.Boolean(), nullable=True),
        sa.Column("in_doaj", sa.Boolean(), nullable=True),
        sa.Column("apc_usd", sa.Integer(), nullable=True),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("mean_citedness", sa.Float(), nullable=True),
        sa.Column("works_count", sa.Integer(), nullable=True),
        sa.Column("medline_indexed", sa.Boolean(), nullable=True),
        sa.Column("topic_works", sa.Integer(), server_default="0", nullable=False),
        sa.Column("included_study_reports", sa.Integer(), server_default="0", nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "reasons", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "warnings", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("shortlisted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "openalex_id", name="uq_journal_candidate"),
    )
    op.create_index(op.f("ix_journal_candidates_project_id"), "journal_candidates", ["project_id"], unique=False)
    op.create_table(
        "review_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "changelog", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("released_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["released_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "version", name="uq_review_release"),
    )
    op.create_index(op.f("ix_review_releases_project_id"), "review_releases", ["project_id"], unique=False)
    op.create_table(
        "surveillance_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("acknowledged_by_id", sa.Integer(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveillance_alerts_project_id"), "surveillance_alerts", ["project_id"], unique=False)
    op.create_table(
        "watch_feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column(
            "seen_ids", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_watch_feeds_project_id"), "watch_feeds", ["project_id"], unique=False)
    op.create_table(
        "impact_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("candidate_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "baseline", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "provisional",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "shift", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "grade_changes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_impact_assessments_project_id"), "impact_assessments", ["project_id"], unique=False)
    op.create_table(
        "manuscripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("citation_style", sa.String(length=100), nullable=False),
        sa.Column(
            "keywords", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "statements", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "extras", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("evidence_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["evidence_snapshot_id"], ["stage_snapshots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "repository_deposits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sandbox", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("external_id", sa.String(length=200), server_default="", nullable=False),
        sa.Column("concept_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("doi", sa.String(length=255), server_default="", nullable=False),
        sa.Column("url", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("storage_key", sa.String(length=255), server_default="", nullable=False),
        sa.Column(
            "files", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("release_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["release_id"], ["review_releases.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_repository_deposits_project_id"), "repository_deposits", ["project_id"], unique=False)
    op.create_table(
        "surveillance_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("connector", sa.String(length=40), nullable=False),
        sa.Column("frequency_days", sa.Integer(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "thresholds", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["search_strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_surveillance_schedules_next_run_at"), "surveillance_schedules", ["next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_surveillance_schedules_project_id"), "surveillance_schedules", ["project_id"], unique=False
    )
    op.create_table(
        "manuscript_authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manuscript_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("email", sa.String(length=320), server_default="", nullable=False),
        sa.Column("affiliation", sa.Text(), server_default="", nullable=False),
        sa.Column("orcid", sa.String(length=40), server_default="", nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("corresponding", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "credit_roles",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("competing_interests", sa.Text(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manuscript_authors_manuscript_id"), "manuscript_authors", ["manuscript_id"], unique=False)
    op.create_table(
        "manuscript_checklist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manuscript_id", sa.Integer(), nullable=False),
        sa.Column("checklist", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="", nullable=False),
        sa.Column("location", sa.Text(), server_default="", nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manuscript_id", "checklist", "item_id", name="uq_manuscript_checklist_item"),
    )
    op.create_index(
        op.f("ix_manuscript_checklist_items_manuscript_id"),
        "manuscript_checklist_items",
        ["manuscript_id"],
        unique=False,
    )
    op.create_table(
        "manuscript_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manuscript_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manuscript_id", "key", name="uq_manuscript_section"),
    )
    op.create_index(
        op.f("ix_manuscript_sections_manuscript_id"), "manuscript_sections", ["manuscript_id"], unique=False
    )
    op.create_table(
        "manuscript_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manuscript_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manuscript_id"], ["manuscripts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("manuscript_id", "number", name="uq_manuscript_version"),
    )
    op.create_index(
        op.f("ix_manuscript_versions_manuscript_id"), "manuscript_versions", ["manuscript_id"], unique=False
    )
    op.create_table(
        "surveillance_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("query", sa.Text(), server_default="", nullable=False),
        sa.Column("database", sa.String(length=200), server_default="", nullable=False),
        sa.Column("retrieved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("new_candidates", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicates", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["surveillance_schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveillance_runs_project_id"), "surveillance_runs", ["project_id"], unique=False)
    op.create_index(op.f("ix_surveillance_runs_schedule_id"), "surveillance_runs", ["schedule_id"], unique=False)
    op.create_table(
        "author_approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["manuscript_authors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["version_id"], ["manuscript_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "author_id", name="uq_author_approval"),
    )
    op.create_index(op.f("ix_author_approvals_version_id"), "author_approvals", ["version_id"], unique=False)
    op.create_table(
        "claim_acknowledgements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("sentence_hash", sa.String(length=64), nullable=False),
        sa.Column("sentence", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("acknowledged_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "sentence_hash", name="uq_claim_acknowledgement"),
    )
    op.create_index(
        op.f("ix_claim_acknowledgements_section_id"), "claim_acknowledgements", ["section_id"], unique=False
    )
    op.create_table(
        "manuscript_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("csl", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("doi", sa.String(length=255), server_default="", nullable=False),
        sa.Column("pmid", sa.String(length=20), server_default="", nullable=False),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column(
            "verification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("retracted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "retraction", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manuscript_references_project_id"), "manuscript_references", ["project_id"], unique=False)
    op.create_table(
        "manuscript_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("suggestion_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manuscript_revisions_section_id"), "manuscript_revisions", ["section_id"], unique=False)
    op.create_table(
        "journal_guidelines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("journal_name", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("file_name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ai_run_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journal_guidelines_project_id"), "journal_guidelines", ["project_id"], unique=False)
    op.create_table(
        "manuscript_suggestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("instruction", sa.Text(), server_default="", nullable=False),
        sa.Column("original", sa.Text(), server_default="", nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "problems", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("ai_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decided_by_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["decided_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["section_id"], ["manuscript_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_suggestions_section_id"), "manuscript_suggestions", ["section_id"], unique=False
    )
    op.create_table(
        "review_rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("journal", sa.String(length=500), server_default="", nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=40), server_default="", nullable=False),
        sa.Column("received_on", sa.String(length=20), server_default="", nullable=False),
        sa.Column("manuscript_version_id", sa.Integer(), nullable=True),
        sa.Column("response_letter", sa.Text(), server_default="", nullable=False),
        sa.Column("response_ai_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manuscript_version_id"], ["manuscript_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["response_ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_rounds_project_id"), "review_rounds", ["project_id"], unique=False)
    op.create_table(
        "surveillance_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), server_default="", nullable=False),
        sa.Column("year", sa.String(length=20), server_default="", nullable=False),
        sa.Column("venue", sa.Text(), server_default="", nullable=False),
        sa.Column("doi", sa.String(length=255), server_default="", nullable=False),
        sa.Column("abstract", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "identifiers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("external_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("relevance", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("ai_decision", sa.String(length=20), nullable=True),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("ai_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("decision_reason", sa.Text(), server_default="", nullable=False),
        sa.Column("decided_by_id", sa.Integer(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["decided_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["surveillance_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_surveillance_candidates_project_id"), "surveillance_candidates", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_surveillance_candidates_run_id"), "surveillance_candidates", ["run_id"], unique=False)
    op.create_table(
        "reviewer_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.Integer(), nullable=False),
        sa.Column("reviewer", sa.String(length=100), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=30), server_default="", nullable=False),
        sa.Column("response", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "changes", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("reanalysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["review_rounds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviewer_comments_round_id"), "reviewer_comments", ["round_id"], unique=False)
    op.create_table(
        "submission_packages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("manuscript_version_id", sa.Integer(), nullable=True),
        sa.Column("guideline_id", sa.Integer(), nullable=True),
        sa.Column("journal_name", sa.String(length=500), server_default="", nullable=False),
        sa.Column("cover_letter", sa.Text(), server_default="", nullable=False),
        sa.Column("cover_letter_ai_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "highlights", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("storage_key", sa.String(length=255), server_default="", nullable=False),
        sa.Column("sha256", sa.String(length=64), server_default="", nullable=False),
        sa.Column(
            "files", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column(
            "readiness", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("confirmed_by_id", sa.Integer(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["confirmed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["cover_letter_ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["guideline_id"], ["journal_guidelines.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["manuscript_version_id"], ["manuscript_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submission_packages_project_id"), "submission_packages", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submission_packages_project_id"), table_name="submission_packages")
    op.drop_table("submission_packages")
    op.drop_index(op.f("ix_reviewer_comments_round_id"), table_name="reviewer_comments")
    op.drop_table("reviewer_comments")
    op.drop_index(op.f("ix_surveillance_candidates_run_id"), table_name="surveillance_candidates")
    op.drop_index(op.f("ix_surveillance_candidates_project_id"), table_name="surveillance_candidates")
    op.drop_table("surveillance_candidates")
    op.drop_index(op.f("ix_review_rounds_project_id"), table_name="review_rounds")
    op.drop_table("review_rounds")
    op.drop_index(op.f("ix_manuscript_suggestions_section_id"), table_name="manuscript_suggestions")
    op.drop_table("manuscript_suggestions")
    op.drop_index(op.f("ix_journal_guidelines_project_id"), table_name="journal_guidelines")
    op.drop_table("journal_guidelines")
    op.drop_index(op.f("ix_manuscript_revisions_section_id"), table_name="manuscript_revisions")
    op.drop_table("manuscript_revisions")
    op.drop_index(op.f("ix_manuscript_references_project_id"), table_name="manuscript_references")
    op.drop_table("manuscript_references")
    op.drop_index(op.f("ix_claim_acknowledgements_section_id"), table_name="claim_acknowledgements")
    op.drop_table("claim_acknowledgements")
    op.drop_index(op.f("ix_author_approvals_version_id"), table_name="author_approvals")
    op.drop_table("author_approvals")
    op.drop_index(op.f("ix_surveillance_runs_schedule_id"), table_name="surveillance_runs")
    op.drop_index(op.f("ix_surveillance_runs_project_id"), table_name="surveillance_runs")
    op.drop_table("surveillance_runs")
    op.drop_index(op.f("ix_manuscript_versions_manuscript_id"), table_name="manuscript_versions")
    op.drop_table("manuscript_versions")
    op.drop_index(op.f("ix_manuscript_sections_manuscript_id"), table_name="manuscript_sections")
    op.drop_table("manuscript_sections")
    op.drop_index(op.f("ix_manuscript_checklist_items_manuscript_id"), table_name="manuscript_checklist_items")
    op.drop_table("manuscript_checklist_items")
    op.drop_index(op.f("ix_manuscript_authors_manuscript_id"), table_name="manuscript_authors")
    op.drop_table("manuscript_authors")
    op.drop_index(op.f("ix_surveillance_schedules_project_id"), table_name="surveillance_schedules")
    op.drop_index(op.f("ix_surveillance_schedules_next_run_at"), table_name="surveillance_schedules")
    op.drop_table("surveillance_schedules")
    op.drop_index(op.f("ix_repository_deposits_project_id"), table_name="repository_deposits")
    op.drop_table("repository_deposits")
    op.drop_table("manuscripts")
    op.drop_index(op.f("ix_impact_assessments_project_id"), table_name="impact_assessments")
    op.drop_table("impact_assessments")
    op.drop_index(op.f("ix_watch_feeds_project_id"), table_name="watch_feeds")
    op.drop_table("watch_feeds")
    op.drop_index(op.f("ix_surveillance_alerts_project_id"), table_name="surveillance_alerts")
    op.drop_table("surveillance_alerts")
    op.drop_index(op.f("ix_review_releases_project_id"), table_name="review_releases")
    op.drop_table("review_releases")
    op.drop_index(op.f("ix_journal_candidates_project_id"), table_name="journal_candidates")
    op.drop_table("journal_candidates")
    # ### end Alembic commands ###
