"""Password resets, email verification, two-factor sign-in, and account deletion; plans, subscriptions, and
billing webhooks; operations heartbeats

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-16 19:58:47.179274
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016"
down_revision: str | Sequence[str] | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "event_id", name="uq_billing_event"),
    )
    op.create_table(
        "ops_heartbeats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("monthly_price_cents", sa.Integer(), nullable=True),
        sa.Column("yearly_price_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column(
            "limits", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column(
            "provider_prices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("public", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "auth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_auth_tokens_user_id"), "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("interval", sa.String(length=10), server_default="none", nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_customer_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=100), server_default="", nullable=False),
        sa.Column("note", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(user_id IS NULL) <> (organization_id IS NULL)", name="ck_subscription_one_account"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_provider_subscription_id"), "subscriptions", ["provider_subscription_id"], unique=False
    )
    op.create_index(
        "uq_subscription_organization",
        "subscriptions",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "uq_subscription_user",
        "subscriptions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.add_column("users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("terms_version", sa.String(length=20), server_default="", nullable=False))
    op.add_column("users", sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("users", sa.Column("mfa_secret_encrypted", sa.LargeBinary(), nullable=True))
    op.add_column("users", sa.Column("mfa_last_step", sa.Integer(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "mfa_recovery_hashes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # The models require these columns; older migrations left them nullable. Orphan rows (none are created by the app)
    # are removed so the constraint can apply.
    op.execute("DELETE FROM review_settings WHERE project_id IS NULL")
    op.execute("DELETE FROM study_reports WHERE record_id IS NULL")
    op.alter_column("review_settings", "project_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("study_reports", "record_id", existing_type=sa.INTEGER(), nullable=False)

    # Existing accounts predate email verification; treat them as verified so requiring it locks nobody out.
    op.execute("UPDATE users SET email_verified_at = created_at WHERE email_verified_at IS NULL")

    # Starting plans. Prices and limits are placeholders to review before launch; administrators edit them in the app.
    plans = sa.table(
        "plans",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("monthly_price_cents", sa.Integer),
        sa.column("yearly_price_cents", sa.Integer),
        sa.column("currency", sa.String),
        sa.column("limits", postgresql.JSONB),
        sa.column("provider_prices", postgresql.JSONB),
        sa.column("public", sa.Boolean),
        sa.column("active", sa.Boolean),
        sa.column("position", sa.Integer),
    )

    def limits(projects, members, records, credits, storage_mb, living, compute, api, webhooks):
        return {
            "projects": projects,
            "members_per_project": members,
            "records_per_month": records,
            "ai_credits_per_month": credits,
            "storage_mb": storage_mb,
            "living_schedules": living,
            "compute_minutes_per_month": compute,
            "api_access": api,
            "webhooks": webhooks,
        }

    op.bulk_insert(
        plans,
        [
            {
                "code": "free",
                "name": "Free",
                "description": "Try OmniReview on one small review.",
                "monthly_price_cents": 0,
                "yearly_price_cents": 0,
                "currency": "USD",
                "limits": limits(1, 3, 2000, 200, 500, 0, 30, False, False),
                "provider_prices": {},
                "public": True,
                "active": True,
                "position": 0,
            },
            {
                "code": "researcher",
                "name": "Researcher",
                "description": "For an individual researcher running several reviews.",
                "monthly_price_cents": 2900,
                "yearly_price_cents": 29000,
                "currency": "USD",
                "limits": limits(5, 5, 20000, 5000, 5000, 2, 300, True, False),
                "provider_prices": {},
                "public": True,
                "active": True,
                "position": 1,
            },
            {
                "code": "team",
                "name": "Team",
                "description": "For review teams with living reviews and integrations.",
                "monthly_price_cents": 9900,
                "yearly_price_cents": 99000,
                "currency": "USD",
                "limits": limits(25, 25, 100000, 25000, 50000, 10, 1500, True, True),
                "provider_prices": {},
                "public": True,
                "active": True,
                "position": 2,
            },
            {
                "code": "institution",
                "name": "Institution",
                "description": "Unlimited use for a university, guideline body, or company, invoiced annually.",
                "monthly_price_cents": None,
                "yearly_price_cents": None,
                "currency": "USD",
                "limits": limits(None, None, None, None, None, None, None, True, True),
                "provider_prices": {},
                "public": True,
                "active": True,
                "position": 3,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("study_reports", "record_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("review_settings", "project_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "deletion_requested_at")
    op.drop_column("users", "mfa_recovery_hashes")
    op.drop_column("users", "mfa_last_step")
    op.drop_column("users", "mfa_secret_encrypted")
    op.drop_column("users", "mfa_enabled")
    op.drop_column("users", "terms_version")
    op.drop_column("users", "terms_accepted_at")
    op.drop_column("users", "password_changed_at")
    op.drop_column("users", "email_verified_at")
    op.drop_index("uq_subscription_user", table_name="subscriptions", postgresql_where=sa.text("user_id IS NOT NULL"))
    op.drop_index(
        "uq_subscription_organization",
        table_name="subscriptions",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_subscriptions_provider_subscription_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_auth_tokens_user_id"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_table("plans")
    op.drop_table("ops_heartbeats")
    op.drop_table("billing_events")
    # ### end Alembic commands ###
