"""Customers' choices: which API keys AI tasks use, and an account's own S3-compatible bucket for stored files

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-17 08:26:39.865819
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0017"
down_revision: str | Sequence[str] | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("endpoint_url", sa.String(length=500), server_default="", nullable=False),
        sa.Column("region", sa.String(length=60), server_default="", nullable=False),
        sa.Column("bucket", sa.String(length=63), nullable=False),
        sa.Column("key_prefix", sa.String(length=200), server_default="", nullable=False),
        sa.Column("access_key_id_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("secret_access_key_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("access_key_last_four", sa.String(length=4), nullable=False),
        sa.Column("use_for_new_files", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("pending_move", sa.String(length=20), nullable=True),
        sa.Column("move_error", sa.Text(), server_default="", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(user_id IS NULL) <> (organization_id IS NULL)", name="ck_storage_connection_one_account"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_storage_connection_organization",
        "storage_connections",
        ["organization_id"],
        unique=True,
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.create_index(
        "uq_storage_connection_user",
        "storage_connections",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.add_column("users", sa.Column("ai_key_mode", sa.String(length=10), server_default="auto", nullable=False))
    # ### end Alembic commands ###
    # Every seeded plan may use its own storage; administrators can turn this off per plan.
    op.execute("""UPDATE plans SET limits = limits || '{"bring_your_own_storage": true}'::jsonb""")


def downgrade() -> None:
    op.execute("UPDATE plans SET limits = limits - 'bring_your_own_storage'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "ai_key_mode")
    op.drop_index(
        "uq_storage_connection_user", table_name="storage_connections", postgresql_where=sa.text("user_id IS NOT NULL")
    )
    op.drop_index(
        "uq_storage_connection_organization",
        table_name="storage_connections",
        postgresql_where=sa.text("organization_id IS NOT NULL"),
    )
    op.drop_table("storage_connections")
    # ### end Alembic commands ###
