"""A prepaid AI balance in place of monthly credits, and the storage each plan includes

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-20 08:13:25.020834
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0018"
down_revision: str | Sequence[str] | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_credit_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("description", sa.String(length=300), server_default="", nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("ai_run_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(user_id IS NULL) <> (organization_id IS NULL)", name="ck_ai_credit_one_account"),
        sa.ForeignKeyConstraint(["ai_run_id"], ["ai_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference", name="uq_ai_credit_reference"),
    )
    op.create_index(op.f("ix_ai_credit_entries_created_at"), "ai_credit_entries", ["created_at"], unique=False)
    op.create_index("ix_ai_credit_organization", "ai_credit_entries", ["organization_id"], unique=False)
    op.create_index("ix_ai_credit_user", "ai_credit_entries", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # AI on the server's keys is paid from the prepaid balance at the published per-token price, so the monthly
    # credit allowance goes. Work on a user's own key stays free of charge, as it always was.
    op.execute("UPDATE plans SET limits = limits - 'ai_credits_per_month'")
    # Storage included with each plan, in MB. Institution keeps unlimited: those customers connect their own bucket.
    for code, storage_mb in (("free", 100), ("researcher", 500), ("team", 1024)):
        op.execute(
            f"UPDATE plans SET limits = jsonb_set(limits, '{{storage_mb}}', '{storage_mb}') WHERE code = '{code}'"
        )


def downgrade() -> None:
    for code, storage_mb, credits in (("free", 500, 200), ("researcher", 5000, 5000), ("team", 50000, 25000)):
        op.execute(
            f"UPDATE plans SET limits = jsonb_set(limits, '{{storage_mb}}', '{storage_mb}') WHERE code = '{code}'"
        )
        op.execute(
            f"UPDATE plans SET limits = jsonb_set(limits, '{{ai_credits_per_month}}', '{credits}') "
            f"WHERE code = '{code}'"
        )
    op.execute(
        "UPDATE plans SET limits = jsonb_set(limits, '{ai_credits_per_month}', 'null') WHERE code = 'institution'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_credit_user", table_name="ai_credit_entries")
    op.drop_index("ix_ai_credit_organization", table_name="ai_credit_entries")
    op.drop_index(op.f("ix_ai_credit_entries_created_at"), table_name="ai_credit_entries")
    op.drop_table("ai_credit_entries")
    # ### end Alembic commands ###
